name: counterapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  auto_route: ^8.2.0
  auto_route_generator: ^8.0.0
  bloc: ^8.1.4
  cloud_firestore: ^5.0.2
  connectivity_plus: ^6.0.3
  dio: ^5.4.3+1
  equatable: ^2.0.5
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  firebase_database: ^11.0.3
  firebase_messaging: ^15.0.2
  firebase_storage: ^12.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.1
  flutter_localization: ^0.2.0
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.1
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  loader_overlay: ^4.0.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  provider: ^6.1.2
  retrofit: ^4.1.0
  intl: any
  flutter_gen: ^5.6.0
  l10n_flutter: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: ^8.1.1
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.6.2


flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/Group 1.svg
    - assets/images/google.svg
    - assets/images/Group 2.svg
    - assets/images/Isolation_Mode.svg
    - assets/images/Upload.svg
    - assets/images/grey-9026.gif
    - assets/images/FJE-yDcXEAMsxeD.jpeg
flutter_intl:
  enabled: true